import type { CursorEngine, CursorFrame, CursorEngineOptions } from "./engine"
import type { CursorSettings, CursorTelemetryFile } from "@recordforge/contracts"

// Generated by wasm-pack from packages/cursor-engine. The init function must be
// called before the WasmCursorEngine class can be used.
import init, { WasmCursorEngine } from "../wasm/cursor_engine.js"

const MIN_GAP_THRESHOLD_MS = 120
const DEFAULT_GAP_MULTIPLIER = 8
const DEFAULT_JITTER_THRESHOLD_PX = 1.0
const DEFAULT_MOTION_THRESHOLD_PX = 1.5
const DEFAULT_SMOOTHING_WINDOW = 12
const DEFAULT_IDLE_FADE_MS = 400
const DEFAULT_ADAPTIVE_SPEED_REF = 2000

let initPromise: Promise<void> | null = null

/** Ensure the WASM module is loaded exactly once. */
async function ensureInitialized(): Promise<void> {
  if (initPromise) return initPromise
  // The generated wasm-pack init resolves the .wasm file relative to its own
  // import.meta.url, so no explicit URL is required in a Vite/Tauri build.
  initPromise = init().then(() => undefined)
  return initPromise
}

/** Convert the shared TS engine options into the Rust CursorEngineOptions shape. */
function toWasmOptions(
  telemetry: CursorTelemetryFile,
  options: CursorEngineOptions,
): Record<string, unknown> {
  const expectedIntervalMs = 1000 / (telemetry.sampleRateHz || 60)
  const requestedGap = options.gapThresholdMs ?? expectedIntervalMs * DEFAULT_GAP_MULTIPLIER
  const minGapThresholdMs = Math.max(requestedGap, MIN_GAP_THRESHOLD_MS)

  return {
    gapThresholdMultiplier: 0,
    minGapThresholdMs,
    jitterThresholdPx: options.jitterThresholdPx ?? DEFAULT_JITTER_THRESHOLD_PX,
    motionThresholdPx: options.motionThresholdPx ?? DEFAULT_MOTION_THRESHOLD_PX,
    smoothingWindowSize: options.smoothingWindowSize ?? DEFAULT_SMOOTHING_WINDOW,
    adaptiveSpeedRefPxPerSec: DEFAULT_ADAPTIVE_SPEED_REF,
    idleFadeDurationMs: options.idleFadeDurationMs ?? DEFAULT_IDLE_FADE_MS,
  }
}

/**
 * Create a cursor engine backed by the Rust + WASM implementation.
 *
 * Falls back to the TypeScript engine if WASM is not available, so callers
 * should wrap this in a try/catch and use createCursorEngine as the fallback.
 */
export async function createWasmCursorEngine(
  telemetry: CursorTelemetryFile,
  options: CursorEngineOptions = {},
): Promise<CursorEngine> {
  if (typeof window === "undefined" || typeof WebAssembly === "undefined") {
    throw new Error("WASM cursor engine is only available in the browser")
  }

  await ensureInitialized()

  const telemetryJson = JSON.stringify(telemetry)
  const optionsJson = JSON.stringify(toWasmOptions(telemetry, options))
  const instance = new WasmCursorEngine(telemetryJson, optionsJson)

  return {
    evaluate: (timeMs: number, settings: CursorSettings): CursorFrame => {
      const settingsJson = JSON.stringify(settings)
      const result = instance.evaluate(timeMs, settingsJson)
      return JSON.parse(result) as CursorFrame
    },
    telemetry,
  }
}
