import {
  overlayDisplayListSchema,
  overlayRenderPlanSchema,
  type OverlayDisplayList,
  type OverlayRenderPlan,
} from "@recordforge/contracts"
import { renderOverlayDisplayList, type OverlayCanvasRenderOptions } from "./canvas-renderer"

// Generated by wasm-pack from packages/overlay-engine. The module is initialized once
// before a retained engine can be constructed.
import init, { WasmOverlayEngine } from "../wasm/overlay_engine.js"

export interface OverlayEngine {
  evaluate: (timeMs: number) => OverlayDisplayList
  renderToCanvas: (
    timeMs: number,
    canvas: HTMLCanvasElement,
    options?: OverlayCanvasRenderOptions,
  ) => void
  dispose: () => void
}

let initPromise: Promise<void> | null = null

async function ensureInitialized(): Promise<void> {
  if (typeof window === "undefined" || typeof WebAssembly === "undefined") {
    throw new Error("WASM overlay engine is only available in the browser")
  }
  if (initPromise) return initPromise

  initPromise = init()
    .then(() => undefined)
    .catch((error: unknown) => {
      initPromise = null
      throw error
    })
  return initPromise
}

/** Create the browser adapter for the canonical Rust overlay scene. */
export async function createOverlayWasmEngine(plan: OverlayRenderPlan): Promise<OverlayEngine> {
  const validatedPlan = overlayRenderPlanSchema.parse(plan)
  await ensureInitialized()

  const wasm = new WasmOverlayEngine(JSON.stringify(validatedPlan))
  let isDisposed = false
  const evaluate = (timeMs: number): OverlayDisplayList => {
    if (isDisposed) throw new Error("WASM overlay engine has been disposed")
    const result = JSON.parse(wasm.evaluate(normalizeTimeMs(timeMs))) as unknown
    return overlayDisplayListSchema.parse(result)
  }

  return {
    evaluate,
    renderToCanvas: (
      timeMs: number,
      canvas: HTMLCanvasElement,
      options: OverlayCanvasRenderOptions = {},
    ): void => {
      if (isDisposed) throw new Error("WASM overlay engine has been disposed")
      renderOverlayDisplayList(evaluate(timeMs), canvas, options)
    },
    dispose: (): void => {
      if (isDisposed) return
      isDisposed = true
      wasm.free()
    },
  }
}

function normalizeTimeMs(timeMs: number): number {
  if (!Number.isFinite(timeMs) || timeMs <= 0) return 0
  return Math.min(Math.floor(timeMs), Number.MAX_SAFE_INTEGER)
}
