import { titleDesignSchema, type TitleTemplate } from "@recordforge/domain"
import type { z } from "zod"
import type { PresetCatalog } from "./presets/preset-registry"
import type { TextPresetDefinition, TextPresetRecord, TextPresetValues } from "./text-presets"
import { getTitlePresetGroup, TITLE_APPEARANCE_COLORS } from "./title-preset-helpers"

const base: TextPresetValues = {
  defaultPrimaryText: "A clear point of view",
  width: 1120,
  height: 260,
  alignment: "left",
  fontFamily: "sans",
  fontSize: 72,
  fontWeight: "600",
  ...TITLE_APPEARANCE_COLORS.dark,
  accentColor: "rgb(190, 242, 100)",
  backdropStyle: "solid",
  backdropOpacity: 0.96,
  backdropBlur: 0,
  backdropBorderRadius: 0,
  backdropPaddingX: 48,
  backdropPaddingY: 36,
  shadowEnabled: false,
  shadowColor: "rgba(0, 0, 0, 0.35)",
  shadowBlur: 0,
  // Designed title motion is evaluated by the canonical engine, not a second legacy entrance.
  animationIn: "none",
  animationOut: "none",
  overlayAnimation: {
    inType: "none",
    outType: "none",
    inDurationMs: 450,
    outDurationMs: 300,
    easing: "expo-out",
  },
  autoScaleText: true,
}

function title(
  id: string,
  name: string,
  template: TitleTemplate,
  category: TextPresetDefinition["category"],
  description: string,
  values: Partial<TextPresetValues>,
  design: Omit<z.input<typeof titleDesignSchema>, "version" | "template"> = {},
): TextPresetRecord {
  const titleDesign = titleDesignSchema.parse({ version: 1, template, ...design })
  return {
    id,
    name,
    description,
    category,
    tags: [getTitlePresetGroup(template), template, name.toLowerCase()],
    definition: {
      ...base,
      ...TITLE_APPEARANCE_COLORS[titleDesign.appearance],
      ...(titleDesign.appearance === "transparent" ? { backdropOpacity: 0 } : {}),
      ...values,
      titleDesign,
    },
  }
}

// Geometry is authored against a 1920 x 1080 canvas; only versioned titles opt into scaling.
export const CREATOR_TITLE_PRESET_CATALOG: PresetCatalog<TextPresetValues> = {
  version: 1,
  categories: ["title", "lower-third", "callout", "badge", "minimal"],
  presets: [
    title(
      "text-clean",
      "Clean Text",
      "clean-text",
      "minimal",
      "Quiet, unboxed typography for a clear title or a short thought.",
      {
        defaultPrimaryText: "Make room for better ideas",
        defaultSecondaryText: "A simpler way to work",
        width: 1240,
        height: 240,
        alignment: "center",
        fontSize: 68,
        backdropStyle: "none",
      },
      { appearance: "transparent", motion: "subtle" },
    ),
    title(
      "text-emphasis",
      "Emphasis",
      "emphasis",
      "title",
      "A single accent underline puts the important words first.",
      {
        defaultPrimaryText: "Less noise. More focus.",
        defaultSecondaryText: "Build a workflow that works for you",
        width: 1200,
        height: 300,
        fontFamily: "heading",
        fontSize: 88,
        fontWeight: "700",
      },
      { emphasisText: "More focus.", letterSpacing: -0.02 },
    ),
    title(
      "text-editorial",
      "Editorial Opener",
      "editorial-opener",
      "title",
      "A serif headline, small eyebrow and fine rule for a considered opening.",
      {
        defaultPrimaryText: "The art of starting small",
        defaultSecondaryText: "Good work begins with one useful idea.",
        defaultTagText: "FIELD NOTES / 01",
        width: 1360,
        height: 440,
        fontFamily: "serif",
        fontSize: 100,
        fontWeight: "500",
        accentColor: "rgb(215, 156, 99)",
        backdropPaddingX: 64,
        backdropPaddingY: 48,
      },
      { appearance: "light", letterSpacing: -0.02, lineHeight: 1.1 },
    ),
    title(
      "text-kinetic",
      "Kinetic Hook",
      "kinetic-hook",
      "title",
      "Oversized display type with a quick, purposeful reveal.",
      {
        defaultPrimaryText: "Stop doing it twice.",
        defaultSecondaryText: "One small change. Hours back.",
        defaultTagText: "WORK SMARTER",
        width: 1360,
        height: 420,
        fontFamily: "heading",
        fontSize: 116,
        fontWeight: "800",
        accentColor: "rgb(190, 242, 100)",
      },
      { emphasisText: "twice.", letterSpacing: -0.03, lineHeight: 1.05 },
    ),
    title(
      "text-chapter",
      "Chapter Marker",
      "chapter-marker",
      "title",
      "A confident chapter number and title mark the next part of your story.",
      {
        defaultPrimaryText: "Build the foundation",
        defaultSecondaryText: "Set up your workspace",
        defaultTagText: "02",
        width: 1200,
        height: 320,
        fontFamily: "heading",
        fontSize: 76,
        fontWeight: "600",
        accentColor: "rgb(147, 197, 253)",
      },
    ),
    title(
      "text-speaker",
      "Speaker ID",
      "speaker-id",
      "lower-third",
      "A compact nameplate gives a person and their role a clear hierarchy.",
      {
        defaultPrimaryText: "Jordan Lee",
        defaultSecondaryText: "Product designer",
        defaultTagText: "STUDIO NOTES",
        width: 760,
        height: 220,
        fontSize: 56,
        fontWeight: "600",
        backdropPaddingX: 36,
        backdropPaddingY: 28,
        accentColor: "rgb(147, 197, 253)",
      },
    ),
    title(
      "text-source",
      "Source Credit",
      "source-credit",
      "lower-third",
      "A restrained credit line keeps the source visible without taking over.",
      {
        defaultPrimaryText: "Our World in Data",
        defaultSecondaryText: "ourworldindata.org / 2025",
        defaultTagText: "SOURCE",
        width: 860,
        height: 160,
        fontSize: 36,
        fontWeight: "500",
        backdropPaddingX: 28,
        backdropPaddingY: 22,
      },
      { motion: "subtle" },
    ),
    title(
      "text-step",
      "Step Guide",
      "step-guide",
      "callout",
      "A numbered instruction keeps a tutorial easy to follow.",
      {
        defaultPrimaryText: "Choose your capture area",
        defaultSecondaryText: "Drag to frame only what matters.",
        defaultTagText: "01",
        width: 1040,
        height: 240,
        fontSize: 56,
        accentColor: "rgb(147, 197, 253)",
      },
    ),
    title(
      "text-shortcut",
      "Keyboard Shortcut",
      "shortcut",
      "badge",
      "Monospaced keycaps make a useful shortcut easy to remember.",
      {
        defaultPrimaryText: "Ctrl + Shift + S",
        defaultSecondaryText: "Save a copy",
        defaultTagText: "SHORTCUT",
        width: 820,
        height: 240,
        fontFamily: "mono",
        fontSize: 52,
        backdropBorderRadius: 12,
      },
    ),
    title(
      "text-command",
      "Command Line",
      "command-line",
      "callout",
      "A focused terminal prompt for a command worth copying.",
      {
        defaultPrimaryText: "bun run dev",
        defaultSecondaryText: "Start the development server",
        defaultTagText: "TERMINAL",
        width: 1120,
        height: 260,
        fontFamily: "mono",
        fontSize: 52,
        fontWeight: "500",
        backdropBorderRadius: 12,
      },
    ),
    title(
      "text-note",
      "Note / Tip",
      "note",
      "callout",
      "A small accent marker and practical advice, away from the main action.",
      {
        defaultPrimaryText: "Keep a little breathing room",
        defaultSecondaryText: "Leave space around the area you want to show.",
        defaultTagText: "TIP",
        width: 1040,
        height: 240,
        fontSize: 48,
        fontWeight: "600",
        backdropBorderRadius: 8,
      },
    ),
    title(
      "text-quote",
      "Pull Quote",
      "pull-quote",
      "callout",
      "Generous serif typography lets a memorable thought stand on its own.",
      {
        defaultPrimaryText: "Make the useful thing beautiful.",
        defaultSecondaryText: "Jordan Lee, product designer",
        defaultTagText: "IN CONVERSATION",
        width: 1240,
        height: 380,
        fontFamily: "serif",
        fontSize: 76,
        fontWeight: "500",
        accentColor: "rgb(215, 156, 99)",
        backdropPaddingX: 64,
        backdropPaddingY: 44,
      },
      { appearance: "light", lineHeight: 1.2 },
    ),
    title(
      "text-metric",
      "Metric",
      "metric",
      "badge",
      "A large animated number with enough context to make it meaningful.",
      {
        defaultPrimaryText: "Less time on busywork",
        defaultSecondaryText: "Compared with our previous workflow",
        defaultTagText: "THIS QUARTER",
        width: 920,
        height: 420,
        fontFamily: "heading",
        fontSize: 112,
        fontWeight: "700",
      },
      { metric: { from: 0, to: 42, decimals: 0, prefix: "", suffix: "%" } },
    ),
    title(
      "text-cta",
      "Call to Action",
      "call-to-action",
      "callout",
      "A clear next step with a supporting line and a destination.",
      {
        defaultPrimaryText: "Try it on your next project",
        defaultSecondaryText: "Start small. Make something useful.",
        defaultTagText: "recordforge.app",
        width: 1200,
        height: 320,
        fontFamily: "heading",
        fontSize: 68,
        fontWeight: "600",
        backdropBorderRadius: 12,
      },
    ),
  ],
}
